DialogsAboutDay = DialogsAboutDay or {}

function DialogsAboutDay.loadDialogues()
  BanditDialogues.addDialogue("day-good", "Como está seu dia?", "Meu dia está ótimo, obrigado por perguntar.", 2, 5, 1, 5)
  BanditDialogues.addDialogue("day-good", "Como está seu dia?", "Estou tendo um dia muito produtivo.", 2, 5, 1, 5)
  BanditDialogues.addDialogue("day-good", "Como está seu dia?", "Hoje está sendo um dia tranquilo.", 2, 5, 1, 5)
  BanditDialogues.addDialogue("day-good", "Como está seu dia?", "Estou aproveitando o dia ao máximo.", 2, 5, 1, 5)
  BanditDialogues.addDialogue("day-good", "Como está seu dia?", "Meu dia está cheio de boas surpresas.", 2, 5, 1, 5)
  BanditDialogues.addDialogue("day-good", "Como está seu dia?", "Estou me sentindo muito bem hoje.", 2, 5, 1, 5)
  BanditDialogues.addDialogue("day-good", "Como está seu dia?", "Hoje está sendo um dia maravilhoso.", 2, 5, 1, 5)
  BanditDialogues.addDialogue("day-good", "Como está seu dia?", "Estou tendo um dia muito agradável.", 2, 5, 1, 5)
  BanditDialogues.addDialogue("day-good", "Como está seu dia?", "Meu dia está indo muito bem.", 2, 5, 1, 5)
  BanditDialogues.addDialogue("day-good", "Como está seu dia?", "Estou tendo um dia muito feliz.", 2, 5, 1, 5)
  BanditDialogues.addDialogue("day-good", "Como está seu dia?", "Hoje está sendo um dia excelente.", 2, 5, 1, 5)
  BanditDialogues.addDialogue("day-good", "Como está seu dia?", "Estou aproveitando cada momento do dia.", 2, 5, 1, 5)
  BanditDialogues.addDialogue("day-good", "Como está seu dia?", "Meu dia está sendo muito positivo.", 2, 5, 1, 5)
  BanditDialogues.addDialogue("day-good", "Como está seu dia?", "Estou tendo um dia muito bom.", 2, 5, 1, 5)
  BanditDialogues.addDialogue("day-good", "Como está seu dia?", "Hoje está sendo um dia muito especial.", 2, 5, 1, 5)

  BanditDialogues.addDialogue("day-shit", "Como está seu dia?", "Meu dia está uma droga, para ser honesto.", 2, 5, -2, 2)
  BanditDialogues.addDialogue("day-shit", "Como está seu dia?", "Hoje está sendo um dia horrível.", 2, 5, -2, 2)
  BanditDialogues.addDialogue("day-shit", "Como está seu dia?", "Estou tendo um dia péssimo.", 2, 5, -2, 2)
  BanditDialogues.addDialogue("day-shit", "Como está seu dia?", "Meu dia está cheio de problemas.", 2, 5, -2, 2)
  BanditDialogues.addDialogue("day-shit", "Como está seu dia?", "Hoje está sendo um dia muito ruim.", 2, 5, -2, 2)
  BanditDialogues.addDialogue("day-shit", "Como está seu dia?", "Estou me sentindo muito mal hoje.", 2, 5, -2, 2)
  BanditDialogues.addDialogue("day-shit", "Como está seu dia?", "Meu dia está sendo um desastre.", 2, 5, -2, 2)
  BanditDialogues.addDialogue("day-shit", "Como está seu dia?", "Hoje está sendo um dia terrível.", 2, 5, -2, 2)
  BanditDialogues.addDialogue("day-shit", "Como está seu dia?", "Estou tendo um dia muito difícil.", 2, 5, -2, 2)
  BanditDialogues.addDialogue("day-shit", "Como está seu dia?", "Meu dia está sendo um pesadelo.", 2, 5, -2, 2)
  BanditDialogues.addDialogue("day-shit", "Como está seu dia?", "Hoje está sendo um dia de merda.", 2, 5, -2, 2)
  BanditDialogues.addDialogue("day-shit", "Como está seu dia?", "Estou me sentindo péssimo hoje.", 2, 5, -2, 2)
  BanditDialogues.addDialogue("day-shit", "Como está seu dia?", "Meu dia está sendo um caos.", 2, 5, -2, 2)
  BanditDialogues.addDialogue("day-shit", "Como está seu dia?", "Hoje está sendo um dia muito estressante.", 2, 5, -2, 2)
  BanditDialogues.addDialogue("day-shit", "Como está seu dia?", "Estou tendo um dia muito ruim.", 2, 5, -2, 2)

  BanditDialogues.addDialogue("day-bad", "Como está seu dia?", "Meu dia está péssimo, para ser honesto.", 2, 5, -2, 2)
  BanditDialogues.addDialogue("day-bad", "Como está seu dia?", "Hoje está sendo um dia horrível.", 2, 5, -2, 2)
  BanditDialogues.addDialogue("day-bad", "Como está seu dia?", "Estou tendo um dia muito ruim.", 2, 5, -2, 2)
  BanditDialogues.addDialogue("day-bad", "Como está seu dia?", "Meu dia está cheio de problemas.", 2, 5, -2, 2)
  BanditDialogues.addDialogue("day-bad", "Como está seu dia?", "Hoje está sendo um dia terrível.", 2, 5, -2, 2)
  BanditDialogues.addDialogue("day-bad", "Como está seu dia?", "Estou me sentindo muito mal hoje.", 2, 5, -2, 2)
  BanditDialogues.addDialogue("day-bad", "Como está seu dia?", "Meu dia está sendo um desastre.", 2, 5, -2, 2)
  BanditDialogues.addDialogue("day-bad", "Como está seu dia?", "Hoje está sendo um dia de merda.", 2, 5, -2, 2)
  BanditDialogues.addDialogue("day-bad", "Como está seu dia?", "Estou tendo um dia muito difícil.", 2, 5, -2, 2)
  BanditDialogues.addDialogue("day-bad", "Como está seu dia?", "Meu dia está sendo um pesadelo.", 2, 5, -2, 2)
  BanditDialogues.addDialogue("day-bad", "Como está seu dia?", "Hoje está sendo um dia muito estressante.", 2, 5, -2, 2)
  BanditDialogues.addDialogue("day-bad", "Como está seu dia?", "Estou me sentindo péssimo hoje.", 2, 5, -2, 2)
  BanditDialogues.addDialogue("day-bad", "Como está seu dia?", "Meu dia está sendo um caos.", 2, 5, -2, 2)
  BanditDialogues.addDialogue("day-bad", "Como está seu dia?", "Hoje está sendo um dia muito ruim.", 2, 5, -2, 2)
  BanditDialogues.addDialogue("day-bad", "Como está seu dia?", "Estou tendo um dia péssimo.", 2, 5, -2, 2)

  BanditDialogues.addDialogue("day-wonderful", "Como está seu dia?", "Meu dia está maravilhoso, obrigado por perguntar.", 2, 5, 1, 5)
  BanditDialogues.addDialogue("day-wonderful", "Como está seu dia?", "Estou tendo um dia incrível.", 2, 5, 1, 5)
  BanditDialogues.addDialogue("day-wonderful", "Como está seu dia?", "Hoje está sendo um dia espetacular.", 2, 5, 1, 5)
  BanditDialogues.addDialogue("day-wonderful", "Como está seu dia?", "Estou aproveitando cada momento do dia.", 2, 5, 1, 5)
  BanditDialogues.addDialogue("day-wonderful", "Como está seu dia?", "Meu dia está cheio de coisas boas.", 2, 5, 1, 5)
  BanditDialogues.addDialogue("day-wonderful", "Como está seu dia?", "Estou me sentindo ótimo hoje.", 2, 5, 1, 5)
  BanditDialogues.addDialogue("day-wonderful", "Como está seu dia?", "Hoje está sendo um dia perfeito.", 2, 5, 1, 5)
  BanditDialogues.addDialogue("day-wonderful", "Como está seu dia?", "Estou tendo um dia muito feliz.", 2, 5, 1, 5)
  BanditDialogues.addDialogue("day-wonderful", "Como está seu dia?", "Meu dia está sendo maravilhoso.", 2, 5, 1, 5)
  BanditDialogues.addDialogue("day-wonderful", "Como está seu dia?", "Estou aproveitando ao máximo o dia de hoje.", 2, 5, 1, 5)
  BanditDialogues.addDialogue("day-wonderful", "Como está seu dia?", "Hoje está sendo um dia fantástico.", 2, 5, 1, 5)
  BanditDialogues.addDialogue("day-wonderful", "Como está seu dia?", "Estou tendo um dia muito especial.", 2, 5, 1, 5)
  BanditDialogues.addDialogue("day-wonderful", "Como está seu dia?", "Meu dia está sendo muito positivo.", 2, 5, 1, 5)
  BanditDialogues.addDialogue("day-wonderful", "Como está seu dia?", "Estou me sentindo muito bem hoje.", 2, 5, 1, 5)
  BanditDialogues.addDialogue("day-wonderful", "Como está seu dia?", "Hoje está sendo um dia maravilhoso.", 2, 5, 1, 5)

  BanditDialogues.addDialogue("day-sucks", "Como está seu dia?", "Meu dia está uma porcaria, para ser honesto.", 2, 5, -2, 2)
  BanditDialogues.addDialogue("day-sucks", "Como está seu dia?", "Hoje está sendo um dia péssimo.", 2, 5, -2, 2)
  BanditDialogues.addDialogue("day-sucks", "Como está seu dia?", "Estou tendo um dia horrível.", 2, 5, -2, 2)
  BanditDialogues.addDialogue("day-sucks", "Como está seu dia?", "Meu dia está cheio de problemas.", 2, 5, -2, 2)
  BanditDialogues.addDialogue("day-sucks", "Como está seu dia?", "Hoje está sendo um dia muito ruim.", 2, 5, -2, 2)
  BanditDialogues.addDialogue("day-sucks", "Como está seu dia?", "Estou me sentindo muito mal hoje.", 2, 5, -2, 2)
  BanditDialogues.addDialogue("day-sucks", "Como está seu dia?", "Meu dia está sendo um desastre.", 2, 5, -2, 2)
  BanditDialogues.addDialogue("day-sucks", "Como está seu dia?", "Hoje está sendo um dia terrível.", 2, 5, -2, 2)
  BanditDialogues.addDialogue("day-sucks", "Como está seu dia?", "Estou tendo um dia muito difícil.", 2, 5, -2, 2)
  BanditDialogues.addDialogue("day-sucks", "Como está seu dia?", "Meu dia está sendo um pesadelo.", 2, 5, -2, 2)
  BanditDialogues.addDialogue("day-sucks", "Como está seu dia?", "Hoje está sendo um dia de merda.", 2, 5, -2, 2)
  BanditDialogues.addDialogue("day-sucks", "Como está seu dia?", "Estou me sentindo péssimo hoje.", 2, 5, -2, 2)
  BanditDialogues.addDialogue("day-sucks", "Como está seu dia?", "Meu dia está sendo um caos.", 2, 5, -2, 2)
  BanditDialogues.addDialogue("day-sucks", "Como está seu dia?", "Hoje está sendo um dia muito estressante.", 2, 5, -2, 2)
  BanditDialogues.addDialogue("day-sucks", "Como está seu dia?", "Estou tendo um dia péssimo.", 2, 5, -2, 2)

  BanditDialogues.addDialogue("day-boring", "Como está seu dia?", "Meu dia está muito entediante.", 2, 5, -1, 2)
  BanditDialogues.addDialogue("day-boring", "Como está seu dia?", "Hoje está sendo um dia bem monótono.", 2, 5, -1, 2)
  BanditDialogues.addDialogue("day-boring", "Como está seu dia?", "Estou entediado, nada de novo acontecendo.", 2, 5, -1, 2)
  BanditDialogues.addDialogue("day-boring", "Como está seu dia?", "Meu dia está sem graça, nada interessante.", 2, 5, -1, 2)
  BanditDialogues.addDialogue("day-boring", "Como está seu dia?", "Hoje está sendo um dia bem chato.", 2, 5, -1, 2)
  BanditDialogues.addDialogue("day-boring", "Como está seu dia?", "Estou passando por um dia bem tedioso.", 2, 5, -1, 2)
  BanditDialogues.addDialogue("day-boring", "Como está seu dia?", "Meu dia está muito parado.", 2, 5, -1, 2)
  BanditDialogues.addDialogue("day-boring", "Como está seu dia?", "Hoje está sendo um dia bem devagar.", 2, 5, -1, 2)
  BanditDialogues.addDialogue("day-boring", "Como está seu dia?", "Estou entediado, nada de interessante acontecendo.", 2, 5, -1, 2)
  BanditDialogues.addDialogue("day-boring", "Como está seu dia?", "Meu dia está sem novidades, bem entediante.", 2, 5, -1, 2)
  BanditDialogues.addDialogue("day-boring", "Como está seu dia?", "Hoje está sendo um dia bem sem graça.", 2, 5, -1, 2)
  BanditDialogues.addDialogue("day-boring", "Como está seu dia?", "Estou passando por um dia bem monótono.", 2, 5, -1, 2)
  BanditDialogues.addDialogue("day-boring", "Como está seu dia?", "Meu dia está muito chato.", 2, 5, -1, 2)
  BanditDialogues.addDialogue("day-boring", "Como está seu dia?", "Hoje está sendo um dia bem parado.", 2, 5, -1, 2)
  BanditDialogues.addDialogue("day-boring", "Como está seu dia?", "Estou entediado, nada de novo por aqui.", 2, 5, -1, 2)

  BanditDialogues.addDialogue("day-normal", "Como está seu dia?", "Meu dia está normal, nada de especial.", 2, 5, 0, 3)
  BanditDialogues.addDialogue("day-normal", "Como está seu dia?", "Hoje está sendo um dia comum.", 2, 5, 0, 3)
  BanditDialogues.addDialogue("day-normal", "Como está seu dia?", "Estou tendo um dia normal.", 2, 5, 0, 3)
  BanditDialogues.addDialogue("day-normal", "Como está seu dia?", "Meu dia está indo bem, nada fora do comum.", 2, 5, 0, 3)
  BanditDialogues.addDialogue("day-normal", "Como está seu dia?", "Hoje está sendo um dia típico.", 2, 5, 0, 3)
  BanditDialogues.addDialogue("day-normal", "Como está seu dia?", "Estou tendo um dia regular.", 2, 5, 0, 3)
  BanditDialogues.addDialogue("day-normal", "Como está seu dia?", "Meu dia está tranquilo, nada de novo.", 2, 5, 0, 3)
  BanditDialogues.addDialogue("day-normal", "Como está seu dia?", "Hoje está sendo um dia normal.", 2, 5, 0, 3)
  BanditDialogues.addDialogue("day-normal", "Como está seu dia?", "Estou tendo um dia sem grandes novidades.", 2, 5, 0, 3)
  BanditDialogues.addDialogue("day-normal", "Como está seu dia?", "Meu dia está indo como de costume.", 2, 5, 0, 3)
  BanditDialogues.addDialogue("day-normal", "Como está seu dia?", "Hoje está sendo um dia ordinário.", 2, 5, 0, 3)
  BanditDialogues.addDialogue("day-normal", "Como está seu dia?", "Estou tendo um dia habitual.", 2, 5, 0, 3)
  BanditDialogues.addDialogue("day-normal", "Como está seu dia?", "Meu dia está calmo, nada fora do comum.", 2, 5, 0, 3)
  BanditDialogues.addDialogue("day-normal", "Como está seu dia?", "Hoje está sendo um dia rotineiro.", 2, 5, 0, 3)
  BanditDialogues.addDialogue("day-normal", "Como está seu dia?", "Estou tendo um dia padrão.", 2, 5, 0, 3)
end
